
INSERT INTO `kpidefinitions` (
  `id`,
  `parent_kpi_id`,
  `kpi_number`,
  `type`,
  `name`,
  `description`,
  `metric`,
  `metric_description`,
  `disclaimer`,
  `progression_target`,
  `min_value`,
  `max_value`,
  `created_at`,
  `updated_at`
) VALUES
(1, NULL, '1', 'GLOBAL', 'Level of completion of SUMP measures', 'It is the share (%) of SUMP measures implemented within the SUM project in each LL.', 'percentage', NULL, NULL, 1, 0, 1, NOW(), NOW()),
(2, NULL, '2', 'GLOBAL', 'Community Involvement', 'It is the number of participatory planning or public engagement activities that have been organized in each LL.', 'custom_unit', 'number of activities', NULL, 1, NULL, NULL, NOW(), NOW()),
(3, NULL, '3', 'GLOBAL', 'Balance of pull - push measures', 'It is defined as the ratio between planned or implemented pull measures over the planned or implemented push interventions in each LL.', 'ratio', NULL, NULL, 1, NULL, NULL, NOW(), NOW()),
(4, 3, '3.1', 'GLOBAL', 'planned over implemented', 'It is defined as the ratio between planned or implemented pull measures over the planned or implemented push interventions in each LL.', 'ratio', NULL, NULL, 1, NULL, NULL, NOW(), NOW()),
(5, 3, '3.2', 'GLOBAL', 'implemented over planned', 'It is defined as the ratio between implemented pull measures over the implemented push interventions in each LL.', 'ratio', NULL, NULL, 1, NULL, NULL, NOW(), NOW()),
(6, NULL, '4', 'GLOBAL', 'Number of NSM integrated in the system', 'It is total number of NSMs that have already been integrated in the transport system of each LL.', 'custom_unit', 'number of services', NULL, 0, NULL, NULL, NOW(), NOW()),
(7, NULL, '5', 'GLOBAL', 'Acceptance level of planned/implemented measures', 'It is the share (%) of respondents who accept the planned/implemented interventions in each LL', 'percentage', NULL, NULL, 0, 0, 1, NOW(), NOW()),
(8, NULL, '6', 'GLOBAL', 'Intention level to use NSM', '', 'percentage', NULL, NULL, 0, 0, 1, NOW(), NOW()),
(9, 8, '6.1', 'GLOBAL', 'car-sharing', 'It is the share (%) of respondents who intend to use or continue using NSM', 'percentage', NULL, NULL, 0, 0, 1, NOW(), NOW()),
(10, 8, '6.2', 'GLOBAL', 'micro-mobility', 'It is the share (%) of respondents who intend to use or continue using NSM', 'percentage', NULL, NULL, 0, 0, 1, NOW(), NOW()),
(11, 8, '6.3', 'GLOBAL', 'ride-hailing', 'It is the share (%) of respondents who intend to use or continue using NSM', 'percentage', NULL, NULL, 0, 0, 1, NOW(), NOW()),
(12, NULL, '7', 'GLOBAL', 'Actual door-to-door travel time', '', 'ratio', NULL, NULL, 0, NULL, NULL, NOW(), NOW()),
(13, 12, '7.1', 'GLOBAL', 'car-sharing only', 'It is the actual door-to-door travel time using NSM + PT (alternative  modes) over the actual door-to-door travel time using a private car at peak/off-peak hours in each LL.', 'ratio', NULL, NULL, 0, NULL, NULL, NOW(), NOW()),
(14, 12, '7.2', 'GLOBAL', 'micro-mobility only', 'It is the actual door-to-door travel time using NSM + PT over private car at peak/off-peak hours in each LL.', 'ratio', NULL, NULL, 0, NULL, NULL, NOW(), NOW()),
(15, 12, '7.3', 'GLOBAL', 'ride-hailing and shuttle services only', 'It is the actual door-to-door travel time using NSM + PT over private car at peak/off-peak hours in each LL.', 'ratio', NULL, NULL, 0, NULL, NULL, NOW(), NOW()),
(16, 12, '7.4', 'GLOBAL', 'public Transport only', 'It is the actual door-to-door travel time using NSM + PT over private car at peak/off-peak hours in each LL.', 'ratio', NULL, NULL, 0, NULL, NULL, NOW(), NOW()),
(17, 12, '7.5', 'GLOBAL', 'public transport and car-sharing', 'It is the actual door-to-door travel time using NSM + PT over private car at peak/off-peak hours in each LL.', 'ratio', NULL, NULL, 0, NULL, NULL, NOW(), NOW()),
(18, 12, '7.6', 'GLOBAL', 'public transport and micro-mobility', 'It is the actual door-to-door travel time using NSM + PT over private car at peak/off-peak hours in each LL.', 'ratio', NULL, NULL, 0, NULL, NULL, NOW(), NOW()),
(19, 12, '7.7', 'GLOBAL', 'public transport and ride-hailing or shuttle services', 'It is the actual door-to-door travel time using NSM + PT over private car at peak/off-peak hours in each LL.', 'ratio', NULL, NULL, 0, NULL, NULL, NOW(), NOW()),
(20, NULL, '8', 'GLOBAL', 'Active mobility infrastructure', 'It is the share (%) of road network length with bike lanes, traffic calming measures (30 km/h or less), or pedestrian zones in each LL over the total road network length', 'percentage', NULL, NULL, 0, 0, 1, NOW(), NOW()),
(21, NULL, '9', 'GLOBAL', 'Multimodal integration in stations/stops', 'It is the average percentage (%) of available transport modes (NSM + PT) at mobility hubs in relation to the total number of transport modes operating in each LL.', 'percentage', NULL, NULL, 0, NULL, NULL, NOW(), NOW()),
(22, NULL, '10', 'GLOBAL', 'Travel cost ratio', '', 'ratio', NULL, NULL, 0, NULL, NULL, NOW(), NOW()),
(23, 22, '10.1.1', 'GLOBAL', 'public transport #1', 'It is the mean travel cost of using NSM + PT over the mean travel cost of using private car in each LL.', 'ratio', NULL, NULL, 0, NULL, NULL, NOW(), NOW()),
(24, 22, '10.1.2', 'GLOBAL', 'public transport #2', 'It is the mean travel cost of using NSM + PT over the mean travel cost of using private car in each LL.', 'ratio', NULL, NULL, 0, NULL, NULL, NOW(), NOW()),
(25, 22, '10.1.3', 'GLOBAL', 'public transport #3', 'It is the mean travel cost of using NSM + PT over the mean travel cost of using private car in each LL.', 'ratio', NULL, NULL, 0, NULL, NULL, NOW(), NOW()),
(26, 22, '10.2.1', 'GLOBAL', 'car sharing #1', 'It is the mean travel cost of using NSM + PT over the mean travel cost of using private car in each LL.', 'ratio', NULL, NULL, 0, NULL, NULL, NOW(), NOW()),
(27, 22, '10.2.2', 'GLOBAL', 'car sharing #2', 'It is the mean travel cost of using NSM + PT over the mean travel cost of using private car in each LL.', 'ratio', NULL, NULL, 0, NULL, NULL, NOW(), NOW()),
(28, 22, '10.3.1', 'GLOBAL', 'micro-mobility #1', 'It is the mean travel cost of using NSM + PT over the mean travel cost of using private car in each LL.', 'ratio', NULL, NULL, 0, NULL, NULL, NOW(), NOW()),
(29, 22, '10.3.2', 'GLOBAL', 'micro-mobility #2', 'It is the mean travel cost of using NSM + PT over the mean travel cost of using private car in each LL.', 'ratio', NULL, NULL, 0, NULL, NULL, NOW(), NOW()),
(30, 22, '10.3.3', 'GLOBAL', 'micro-mobility #3', 'It is the mean travel cost of using NSM + PT over the mean travel cost of using private car in each LL.', 'ratio', NULL, NULL, 0, NULL, NULL, NOW(), NOW()),
(31, 22, '10.4.1', 'GLOBAL', 'ride-hailing and shuttle services #1', 'It is the mean travel cost of using NSM + PT over the mean travel cost of using private car in each LL.', 'ratio', NULL, NULL, 0, NULL, NULL, NOW(), NOW()),
(32, 22, '10.4.2', 'GLOBAL', 'ride-hailing and shuttle services #2', 'It is the mean travel cost of using NSM + PT over the mean travel cost of using private car in each LL.', 'ratio', NULL, NULL, 0, NULL, NULL, NOW(), NOW()),
(33, NULL, '11', 'GLOBAL', 'Perceived door-to-door travel time ratio', '', 'ratio', NULL, NULL, 0, NULL, NULL, NOW(), NOW()),
(34, 33, '11.1.1', 'GLOBAL', 'taxi [off-peak]', 'It is the perceived door-to-door travel time using NSM + PT over the perceived door-to-door travel time using a private car at peak/off-peak hours in each LL.', 'ratio', NULL, NULL, 0, NULL, NULL, NOW(), NOW()),
(35, 33, '11.1.2', 'GLOBAL', 'public transport [off-peak]', 'It is the perceived door-to-door travel time using NSM + PT over the perceived door-to-door travel time using a private car at peak/off-peak hours in each LL.', 'ratio', NULL, NULL, 0, NULL, NULL, NOW(), NOW()),
(36, 33, '11.1.3', 'GLOBAL', 'bicycle [off - peak]', 'It is the perceived door-to-door travel time using NSM + PT over the perceived door-to-door travel time using a private car at peak/off-peak hours in each LL.', 'ratio', NULL, NULL, 0, NULL, NULL, NOW(), NOW()),
(37, 33, '11.2.1', 'GLOBAL', 'taxi [peak]', 'It is the perceived door-to-door travel time using NSM + PT over the perceived door-to-door travel time using a private car at peak/off-peak hours in each LL.', 'ratio', NULL, NULL, 0, NULL, NULL, NOW(), NOW()),
(38, 33, '11.2.2', 'GLOBAL', 'public transport [peak]', 'It is the perceived door-to-door travel time using NSM + PT over the perceived door-to-door travel time using a private car at peak/off-peak hours in each LL.', 'ratio', NULL, NULL, 0, NULL, NULL, NOW(), NOW()),
(39, 33, '11.2.3', 'GLOBAL', 'bicycle [peak]', 'It is the perceived door-to-door travel time using NSM + PT over the perceived door-to-door travel time using a private car at peak/off-peak hours in each LL.', 'ratio', NULL, NULL, 0, NULL, NULL, NOW(), NOW()),
(40, NULL, '12', 'GLOBAL', 'Perceived safety', '', 'score', NULL, NULL, 1, -5, 5, NOW(), NOW()),
(41, 40, '12.1.1', 'GLOBAL', 'diff taxi', 'It is the mean difference of perceived safety ratings for each NSM mode over the perceived safety ratings of private car in each LL.', 'score', NULL, NULL, 1, -5, 5, NOW(), NOW()),
(42, 40, '12.1.2', 'GLOBAL', 'diff public transport', 'It is the mean difference of perceived safety ratings for each NSM mode over the perceived safety ratings of private car in each LL.', 'score', NULL, NULL, 1, -5, 5, NOW(), NOW()),
(43, 40, '12.1.3', 'GLOBAL', 'diff personal bicycle', 'It is the mean difference of perceived safety ratings for each NSM mode over the perceived safety ratings of private car in each LL.', 'score', NULL, NULL, 1, -5, 5, NOW(), NOW()),
(44, 40, '12.2.1', 'GLOBAL', 'diff traffic taxi', 'It is the mean difference of perceived safety ratings for each NSM mode over the perceived safety ratings of private car in each LL.', 'score', NULL, NULL, 1, -5, 5, NOW(), NOW()),
(45, 40, '12.2.2', 'GLOBAL', 'diff public transport', 'It is the mean difference of perceived safety ratings for each NSM mode over the perceived safety ratings of private car in each LL.', 'score', NULL, NULL, 1, -5, 5, NOW(), NOW()),
(46, 40, '12.2.3', 'GLOBAL', 'diff bicycle', 'It is the mean difference of perceived safety ratings for each NSM mode over the perceived safety ratings of private car in each LL.', 'score', NULL, NULL, 1, -5, 5, NOW(), NOW()),
(47, NULL, '13', 'GLOBAL', 'User satisfaction', 'It refers to the share (%) of satisfied users (rates 4, 5, and 6) by the provided NSM + PT services in each LL.', 'score', NULL, NULL, 1, -5, 5, NOW(), NOW()),
(48, NULL, '14', 'GLOBAL', 'Perceived affordability', 'It is the perceived share (%) of the monthly household budget spent in travelling.', 'percentage', NULL, NULL, 0, 0, 1, NOW(), NOW()),
(51, NULL, '15', 'GLOBAL', 'Modal Split', '', 'none', NULL, NULL, 1, 0, NULL, NOW(), NOW()),
(52, 51, '15.a', 'GLOBAL', 'Modal Split in trips', '', 'percentage', NULL, NULL, 1, 0, 1, NOW(), NOW()),
(53, 51, '15.b', 'GLOBAL', 'Modal Split in passenger kilometers', '', 'percentage', NULL, NULL, 1, 0, 1, NOW(), NOW()),
(54, 51, '15.c', 'GLOBAL', 'Modal Split in vehicle kilometers', '', 'percentage', NULL, NULL, 1, 0, 1, NOW(), NOW()),
(49, NULL, '16', 'GLOBAL', 'Greenhouse emissions', 'It is the tank-to-wheel and well-to-wheel CO2 emissions (in tons) of all passenger transport modes per inhabitant in each LL.', 'custom_unit', 'tons/y/cap', NULL, 0, 0, 2.75, NOW(), NOW()),
(60, NULL, '17', 'LOCAL', 'Air pollution emissions', 'well-to-wheel air pollutant emissions (in tons) of all passenger transport modes per inhabitant in each LL', 'custom_unit', 'tons/cap/y', NULL, 0, 0, 2.15, NOW(), NOW()),
(61, NULL, '18', 'LOCAL', 'Noise hindrance', 'the percentage of people exposed to different noise bands (i.e., 55–59, 60–64, 65–69, 70-74, > 75 dB) in each LL', 'percentage', NULL, NULL, 0, 0, 1, NOW(), NOW()),
(62, NULL, '19', 'LOCAL', 'Energy consumption ratio', 'The total energy consumption per km of only the passenger transport modes', 'custom_unit', 'MJ/y', NULL, 0, 1.5, 3.5, NOW(), NOW()),
(63, NULL, '20', 'LOCAL', 'Accessibility ratio', 'It is the accessibility provided by NSM and/or Public Transport over the accessibility private by private car', 'ratio', NULL, NULL, 1, 0, NULL, NOW(), NOW()),
(64, NULL, '21', 'LOCAL', 'Horizontal social equity', 'It refers to the distribution of accessibility level among individuals, groups or geographic areas considered equal in capabilities and requirements.', 'ratio', NULL, NULL, 0, 0, 1, NOW(), NOW()),
(65, NULL, '22', 'LOCAL', 'Vertical social equity', 'It refers to the distribution of accessibility level among individuals, groups or geographic areas that differ in needs and abilities in each LL.', 'ratio', NULL, NULL, 0, -1, 1, NOW(), NOW()),
(66, NULL, '23', 'LOCAL', 'Social inclusion', 'It is the inclusion of Public Transport and/or NSM services to persons with reduced mobility.', 'percentage', NULL, NULL, 1, 0, 1, NOW(), NOW()),
(50, NULL, '24', 'GLOBAL', 'Congestion and travel delays', 'It is the average ratio between of travel time at peak hours and off-peak hours considering all transport modes', 'ratio', NULL, NULL, 0, 0, 3, NOW(), NOW()),
(67, NULL, '25', 'LOCAL', 'Social welfare', 'It is defined as the total profits of passengers using NSM and Public Transport, expressed in time savings, plus the total profits of transport operators', 'custom_unit', 'euros', NULL, 1, 0, NULL, NOW(), NOW()),
(68, NULL, '26', 'LOCAL', 'Profitability of NSM operators', 'It is the annual change (%) in total profits of all NSMs that have been integrated in the transport system', 'percentage', NULL, NULL, 1, 0, 1, NOW(), NOW()),
(69, NULL, '27', 'LOCAL', 'Profitability of MaaS platforms', 'It is defined as the percentage change in total profits month-over-month', 'percentage', NULL, NULL, 1, 0, 1, NOW(), NOW()),
(70, NULL, '28', 'LOCAL', 'Operation revenue of NSMs', 'Revenue Per Month (€/Month) for NSM services per LL is a metric that represents the total income generated/ or/ predicted to be generated from the service within a month.', 'custom_unit', 'euros/month', NULL, 1, 0, NULL, NOW(), NOW()),
(71, NULL, '29', 'LOCAL', 'Service utilization rate', 'The proportion of operational vehicles within the entire fleet', 'percentage', NULL, NULL, 1, 0, 1, NOW(), NOW())
