INSERT INTO `projects` (`name`, `description`, `type`, `image_url`, `created_at`, `updated_at`) VALUES
('Congestion charges', 'Fees imposed on vehicles entering designated city areas to reduce traffic congestion.', 'PUSH', '/icons/ticket.svg', NOW(), NOW()),
('Parking charges', 'Increased parking fees to discourage long-term car use and promote modal shift.', 'PUSH', '/icons/parking_sign.svg', NOW(), NOW()),
('Restricted parking', 'Reductions in available public parking to limit car access, especially in central zones.', 'PUSH', '/icons/no_cars.svg', NOW(), NOW()),
('Limited traffic zone / Pedestrianisation of streets', 'Car-free or low-emission zones that prioritize pedestrians, cyclists, and shared mobility.', 'PUSH', '/icons/pedestrian.svg', NOW(), NOW()),
('Parking supply management', 'Policies that reduce or restructure parking supply to manage demand and encourage alternatives.', 'PUSH', '/icons/parking_sign.svg', NOW(), NOW()),
('Speed limits', 'Lowering vehicle speed limits to improve safety and promote non-motorized travel.', 'PUSH', '/icons/30sign.svg', NOW(), NOW()),
('Mobility hubs', 'Centralized locations where multiple transport modes (e.g., bikes, buses, taxis) are integrated.', 'PULL', '/icons/cityz_zones.svg', NOW(), NOW()),
('Scheduling integration in MaaS services', 'Coordinated schedules across transport services to streamline connections.', 'PULL', '/icons/time_table.svg', NOW(), NOW()),
('Ticketing integration in MaaS services', 'Unified or digital ticketing across services to simplify travel.', 'PULL', '/icons/mobile.svg', NOW(), NOW()),
('Improved NSM infrastructure, e.g. bike lanes & "park & ride"', 'New infrastructure like bike lanes, "park & ride" stations to support non-car travel.', 'PULL', '/icons/bike_lane.svg', NOW(), NOW()),
('On demand vehicle sharing action plan', 'Access to shared vehicles (cars, bikes, e-scooters) on demand via apps or stations.', 'PULL', '/icons/mobile.svg', NOW(), NOW()),
('Nudging (gamification or rewards)', 'Use of rewards or games to encourage use of shared or sustainable transport.', 'PULL', '/icons/kid1.svg', NOW(), NOW()),
('Dynamic pricing of NSM', 'Flexible pricing (e.g., cheaper off-peak rides) to balance demand and promote use.', 'PULL', '/icons/ticket.svg', NOW(), NOW()),
('Improved information about the availability of shared modes', 'Real-time data on vehicle availability and travel options via digital platforms.', 'PULL', '/icons/mobile.svg', NOW(), NOW()),
('Introduction of new NSM services', 'Launch of bike-sharing, scooter-sharing, or other new transport options.', 'PULL', '/icons/e-scooter.svg', NOW(), NOW()),
('Introduction of new PT infrastructures/lines', 'Deployment of new public transport lines like electric buses or tram extensions.', 'PULL', '/icons/metro_tunnel.svg', NOW(), NOW()),
('Streets retrofitting/introduction of priority lanes', 'Street redesign for better walking/cycling and priority lanes for buses or shared modes.', 'PULL', '/icons/cityz_zones.svg', NOW(), NOW()),
('Dedicated parking spaces for carsharing/micromobility', 'Reserved spaces to support the use of shared cars or micromobility vehicles.', 'PULL', '/icons/bycicle_parking.svg', NOW(), NOW()),
('Widening PT geographical area', 'Extending public transport coverage to reach underserved zones.', 'PULL', '/icons/metro_map.svg', NOW(), NOW()),
('Central PT planning and construction program', 'Comprehensive public transport network planning to enhance coordination and efficiency.', 'PULL', '/icons/cityz_zones.svg', NOW(), NOW());
